# FROM 3.16.2
# EXPOSE 3000 5000
# 
# WORKDIR /home/app
# 
# COPY package.json /home/app/
# COPY package-lock.json /home/app/
# 
# RUN npm ci
# 
# COPY . /home/app
# 
# RUN npm run build
# 
# CMD ./scripts/start.sh

# https://michalzalecki.com/docker-compose-for-nodejs-and-postgresql/
