version: '3.1'

services:
  psql:
    container_name: psql
    image: postgres
    restart: on-failure
    env_file: pong/.env
    networks:
      - dream
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PSQL_DATABASE}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    env_file: pong/.env
    networks:
      - dream
    ports:
      - 8080:8080

networks:
  dream:
    name: dream
    driver: bridge
